from django.db import models

class ListPC(models.Model):
  id = models.AutoField(primary_key='True')
  location = models.CharField(max_length=255)
  departement = models.CharField(max_length=255)
  user = models.CharField(max_length=255)
  devicetype = models.CharField(max_length=255)
  devicestatus = models.CharField(max_length=255)
  oldlabel = models.CharField(max_length=255)
  newlabel = models.CharField(max_length=255)
  mainboard = models.CharField(max_length=255)
  processor = models.CharField(max_length=255)
  memory = models.CharField(max_length=255)
  hardisk = models.CharField(max_length=255)
  monitor1oldlabel = models.CharField(max_length=255)
  monitor1newlabel = models.CharField(max_length=255)
  monitor1model = models.CharField(max_length=255)
  monitor1size = models.CharField(max_length=255)
  monitor2oldlabel = models.CharField(max_length=255)
  monitor2newlabel = models.CharField(max_length=255)
  monitor2model = models.CharField(max_length=255)
  monitor2size = models.CharField(max_length=255)
  ipaddress = models.CharField(max_length=255)
  internet = models.CharField(max_length=255)
  os = models.CharField(max_length=255)
  licenseos = models.CharField(max_length=255)
  office = models.CharField(max_length=255)
  licenseoffice = models.CharField(max_length=255)
  application = models.CharField(max_length=255)
  purchasedate = models.CharField(max_length=255)
  grade = models.CharField(max_length=255)
  antivirus = models.CharField(max_length=255)
  scandate = models.CharField(max_length=255)
  result = models.CharField(max_length=255)
  checkedby = models.CharField(max_length=255)
  checkeddate = models.CharField(max_length=255)
  remark = models.CharField(max_length=255)